# Generated by Django 5.0.3 on 2024-03-27 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_customer_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='username',
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=2, max_length=10, validators=[django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
    ]
